# On définit le niveau général sur ERROR
rootLogger.level = error
rootLogger.appenderRef.stdout.ref = console

# Configuration de la sortie console
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# On s'assure que Spark et Hadoop restent silencieux
logger.spark.name = org.apache.spark
logger.spark.level = error

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = error
